version: '3.9'

services:
  frontend:
    image: ${YCR_REGISTRY}/${YCR_FRONT_IMAGE_NAME}:${IMAGE_TAG}
    container_name: selforg_frontend
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
    restart: always
    networks:
      - selforg_net

networks:
  selforg_net:
    external: true
    name: selforg_net
